
export const INITIAL_PLACEHOLDERS = [
    "CHAN 1 THRU 100 @ FULL ENTER",
    "RECORD MACRO 101 # EOS_AUTOMATION",
    "QUERY: HOW TO PATCH MULTICELL FIXTURES?",
    "LOAD SHOWFILE: 'LUMINA_SCRIPTS_V2.3'",
    "SET OSC_PORT 8000 # CONNECTING_RESOLUME",
    "DISPLAY MAGIC_SHEET 50 # 3D_VIEW"
];
